# Generated by Django 4.1.2 on 2022-10-18 10:53

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=256, unique=True)),
                ("creater_name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=256, unique=True)),
                ("test_duration", models.DurationField()),
                (
                    "fk_course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=600, unique=True)),
                ("option_a", models.TextField(max_length=600)),
                ("option_b", models.TextField(max_length=600)),
                ("option_c", models.TextField(max_length=600)),
                ("option_d", models.TextField(max_length=600)),
                (
                    "answer",
                    models.TextField(
                        max_length=600, validators=[course.models.answer_validator]
                    ),
                ),
                (
                    "fk_test_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.test"
                    ),
                ),
            ],
        ),
    ]
