# Generated by Django 4.1.2 on 2022-10-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_rename_fk_test_id_question_fk_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="test_duration",
            field=models.DurationField(),
        ),
    ]
