# Generated by Django 4.1.2 on 2022-10-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="fk_course_id",
            new_name="fk_course",
        ),
        migrations.AlterField(
            model_name="test",
            name="test_duration",
            field=models.IntegerField(),
        ),
    ]
