# Generated by Django 4.1.2 on 2022-10-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_creater_name_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creater_name',
            field=models.CharField(max_length=256),
        ),
    ]
