# Generated by Django 4.1.2 on 2022-10-28 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0011_alter_course_creater_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creater_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
