# Generated by Django 4.1.2 on 2022-10-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staff",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_no",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="staff",
            unique_together={("phone_number", "email", "staff_no")},
        ),
    ]
